name: Build and Upload Artifacts

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/LCAmmoCheck.csproj') }}

      - name: Build and Publish
        run: |
          dotnet restore
          dotnet build LCAmmoCheck/LCAmmoCheck.csproj -c Release --output ./publish
          dotnet publish LCAmmoCheck/LCAmmoCheck.csproj -c Release --output ./publish

      - name: Upload artifact (dll)
        uses: actions/upload-artifact@v4
        with:
          name: DLL-Release
          path: ./publish/LCAmmoCheck.dll

      - name: Upload artifact (Thunderstore)
        uses: actions/upload-artifact@v4
        with:
          name: Thunderstore-Release
          path: ./publish/LCAmmoCheck-*.zip
