name: Publish Release

on:
  workflow_run:
    workflows: ["Build and Upload Artifacts"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  download_and_release:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success'
      )
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if version changed
        if: github.event.workflow_run.event != 'workflow_dispatch'
        id: check_version
        run: |
          if git diff HEAD^ HEAD -- LCAmmoCheck/LCAmmoCheck.csproj | grep -q "<Version>"; then
            echo "Version changed"
            echo "stop_workflow=false" >> $GITHUB_OUTPUT
            echo "VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" LCAmmoCheck/LCAmmoCheck.csproj)" >> $GITHUB_ENV
          else
            echo "Version did not change"
            echo "stop_workflow=true" >> $GITHUB_OUTPUT
          fi

      - name: Set version from input
        if: github.event.workflow_run.event == 'workflow_dispatch'
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Download artifact
        if: steps.check_version.outputs.stop_workflow == 'false'
        uses: actions/download-artifact@v4
        with:
          # DLL-Release and Thunderstore-Release are the artifact names from the build workflow
          pattern: "*-Release"
          merge-multiple: true
          path: ./publish

      - name: Create Release
        if: steps.check_version.outputs.stop_workflow == 'false'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          automatic_releases_tag: ${{ env.VERSION }}
          files: |
            ./publish/LCAmmoCheck.dll
            ./publish/LCAmmoCheck-*.zip
