name: Publish Release to Thunderstore
on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish_to_thunderstore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        run: |
          gh run download --name Thunderstore-Release --dir ./publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get name, description and version
        run: |
          NAME=$(grep -oPm1 "(?<=<PackageId>)[^<]+" LCAmmoCheck/LCAmmoCheck.csproj)
          DESCRIPTION=$(grep -oPm1 "(?<=<Description>)[^<]+" LCAmmoCheck/LCAmmoCheck.csproj)
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" LCAmmoCheck/LCAmmoCheck.csproj)
          echo "NAME=$NAME" >> $GITHUB_ENV
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: GreenTF/upload-thunderstore-package@v4.2
        with:
          namespace: axd1x8a
          description: ${{ env.DESCRIPTION }}
          token: ${{ secrets.THUNDERSTORE_TOKEN }}
          name: ${{ env.NAME }}
          version: ${{ env.VERSION }}
          community: Lethal Company
          repo: lethal-company.thunderstore.io
          file: ./publish/LCAmmoCheck-${{ env.VERSION }}.zip
          categories: |
            clientside
            bepinex
            misc
            mods
